# Adds a Sponsor button on the GitHub repo header. Single supported
# platform for Lamella today. The Apache 2.0 license remains the same
# either way; donations help keep the project actively maintained but
# are never gated against features.
ko_fi: ajquick
