# Copyright 2026 Lamella LLC
# SPDX-License-Identifier: Apache-2.0
#
# Lamella - AI-powered bookkeeping software that provides context-aware financial intelligence
# https://lamella.ai

"""Writer for connector_accounts.bean — the Connector's own registry
of Open/Close directives.

Mirrors the receipt-linker pattern: snapshot the file, append directive
lines, run bean-check, roll back on failure. This file is included from
main.bean via a one-time appended line on first write.

What goes in here:
  - Open directives for entity expense trees (e.g. `Expenses:Acme:Supplies`)
  - Open directives for user-created bank/credit accounts
    (e.g. `Assets:Acme:BankOne:Checking`)
  - Open directives for vehicles and their expense categories
  - Open directives for loans (liability + interest/escrow expense)
  - Close directives when accounts are retired

What does NOT go in here:
  - Transactions (those live in main.bean, simplefin_transactions.bean,
    connector_overrides.bean, historical_*.bean)
  - Receipt links (those live in connector_links.bean)
  - FIXME overrides (those live in connector_overrides.bean)
"""
from __future__ import annotations

import logging
import re
from datetime import date
from pathlib import Path

from lamella.core.fs import validate_safe_path
from lamella.core.ledger_writer import (
    BeanCheckError,
    capture_bean_check,
    ensure_include_in_main,
    run_bean_check,
    run_bean_check_vs_baseline,
)

log = logging.getLogger(__name__)


CONNECTOR_ACCOUNTS_HEADER = (
    "; Managed by Lamella. Do not hand-edit.\n"
    "; Open / Close directives generated by /settings/{entities,accounts,vehicles,loans}.\n"
    "; To rename or retire entries, use the admin UI — it keeps this file in\n"
    "; sync with the SQLite registry and validates every write with bean-check.\n"
)


def ensure_connector_accounts_exists(path: Path) -> bool:
    """Create the file with a header if it doesn't exist yet. Returns
    True when the file was created."""
    if path.exists():
        return False
    safe = validate_safe_path(path, allowed_roots=[path.parent])
    safe.parent.mkdir(parents=True, exist_ok=True)
    safe.write_text(CONNECTOR_ACCOUNTS_HEADER, encoding="utf-8")
    return True


class AccountsWriter:
    """Append Open/Close directives for Connector-created accounts.

    Contract: Beancount stays authoritative. We take a byte-level
    snapshot of the file before writing, run bean-check after, and
    revert on failure so a rejected write leaves the ledger
    byte-identical to its pre-call state.
    """

    def __init__(
        self,
        *,
        main_bean: Path,
        connector_accounts: Path,
        run_check: bool = True,
    ):
        # ADR-0030: validate both paths land inside the ledger directory
        # before any captured-by-instance write touches disk.
        ledger_dir = main_bean.parent
        self.main_bean = validate_safe_path(
            main_bean, allowed_roots=[ledger_dir]
        )
        self.connector_accounts = validate_safe_path(
            connector_accounts, allowed_roots=[ledger_dir]
        )
        self.run_check = run_check

    def _snapshot(self) -> tuple[bytes, bytes | None, bool]:
        main_before = self.main_bean.read_bytes()
        accounts_existed = self.connector_accounts.exists()
        accounts_before = (
            self.connector_accounts.read_bytes() if accounts_existed else None
        )
        return (main_before, accounts_before, accounts_existed)

    def _restore(self, snap: tuple[bytes, bytes | None, bool]) -> None:
        main_before, accounts_before, accounts_existed = snap
        self.main_bean.write_bytes(main_before)
        if not accounts_existed:
            self.connector_accounts.unlink(missing_ok=True)
        else:
            assert accounts_before is not None
            self.connector_accounts.write_bytes(accounts_before)

    def _check(self, baseline: str | None = None) -> None:
        if not self.run_check:
            return
        # If we have a pre-write bean-check snapshot, only fail on NEW
        # errors. That way pre-existing plugin complaints in the user's
        # ledger don't block legitimate admin writes.
        if baseline is not None:
            run_bean_check_vs_baseline(self.main_bean, baseline)
        else:
            run_bean_check(self.main_bean)

    def _append(self, block: str) -> None:
        ensure_connector_accounts_exists(self.connector_accounts)
        ensure_include_in_main(self.main_bean, self.connector_accounts)
        with self.connector_accounts.open("a", encoding="utf-8") as fh:
            if not block.endswith("\n"):
                block += "\n"
            fh.write(block)

    def write_opens(
        self,
        paths: list[str],
        *,
        opened_on: date | None = None,
        comment: str | None = None,
        existing_paths: set[str] | None = None,
        earliest_ref_by_path: dict[str, date] | None = None,
        known_entity_slugs: frozenset[str] | set[str] | None = None,
    ) -> None:
        """Append `{date} open {path}` for each path.

        Idempotent: ``existing_paths`` (e.g. the set of accounts currently
        open in the ledger) tells the writer to skip paths already
        declared — adding them again would fail bean-check with
        "duplicate open."

        Backdate safety: if a path is already *referenced* by an
        earlier posting in the ledger (common when scaffolding
        Schedule A categories against historical imports), the Open
        must be dated on or before that reference — otherwise
        bean-check rejects the whole write as "inactive account."
        Callers that care pass ``earliest_ref_by_path`` (typically
        from a one-pass ledger scan); write_opens dates each Open
        at ``min(opened_on, earliest_ref)``.

        Default ``opened_on`` is ``1900-01-01``. Beancount requires the
        Open date to be on or before any posting against the account,
        so a far-back default lets historical imports land without
        bean-check rejecting them as "inactive account at the time of
        transaction." Callers that genuinely know an account opened
        on a real date (loans, vehicles with a purchase date, the
        wizard's per-account modal) pass ``opened_on`` explicitly. When
        ``earliest_ref_by_path`` is provided and contains an earlier
        date, the per-path Open is written with that earlier date
        instead.

        ``known_entity_slugs``: when provided, every path's second segment
        (for Assets/Liabilities/Expenses/Income roots) must be a member of
        this set — enforcing the ADR-0042 entity-first rule at write time.
        Callers that have a DB connection available should pass
        ``frozenset(r["slug"] for r in conn.execute("SELECT slug FROM entities"))``
        so structural errors are caught here rather than at bean-check time.
        When omitted, only the ADR-0045 segment-character rule is enforced.
        """
        if not paths:
            return
        # Validate every path against ADR-0045 BEFORE the write so a
        # syntax-invalid segment ("eBay", "1stCard") raises here with
        # the offending segment named, instead of failing later as a
        # generic bean-check parser error after the .bean file was
        # already mutated and rolled back.
        from lamella.core.registry.service import (
            InvalidAccountSegmentError,
            validate_beancount_account,
            validate_entity_first_path,
        )
        for p in paths:
            if not p:
                continue
            try:
                validate_beancount_account(p)
            except InvalidAccountSegmentError:
                raise  # surface to caller; do not start the write
            # ADR-0042: enforce entity-first rule when the caller
            # supplies the known entity registry.  This catches paths
            # like ``Assets:Vehicles:VAcmeVan2`` (category
            # label in entity position) before the write lands on disk.
            if known_entity_slugs is not None:
                try:
                    validate_entity_first_path(p, known_entity_slugs)
                except InvalidAccountSegmentError:
                    raise  # surface to caller; do not start the write
        # Filter duplicates within our own write and against the ledger.
        existing = set(existing_paths or ())
        filtered: list[str] = []
        seen: set[str] = set()
        for p in paths:
            if not p or p in seen or p in existing:
                continue
            seen.add(p)
            filtered.append(p)
        if not filtered:
            return
        default_date = opened_on or date(1900, 1, 1)
        earliest_map = earliest_ref_by_path or {}
        _, baseline_output = capture_bean_check(self.main_bean)
        snap = self._snapshot()
        try:
            lines: list[str] = []
            if comment:
                lines.append(f"\n; {comment}\n")
            for p in filtered:
                ref_date = earliest_map.get(p)
                # Open has to be <= earliest reference; otherwise
                # Beancount rejects every prior posting as
                # "inactive account."
                if ref_date is not None and ref_date < default_date:
                    effective_date = ref_date
                else:
                    effective_date = default_date
                lines.append(f"{effective_date.isoformat()} open {p}\n")
            self._append("".join(lines))
            self._check(baseline=baseline_output)
        except BeanCheckError:
            self._restore(snap)
            raise
        except Exception:
            self._restore(snap)
            raise

    def write_close(
        self,
        path: str,
        *,
        closed_on: date | None = None,
    ) -> None:
        closed = closed_on or date.today()
        _, baseline_output = capture_bean_check(self.main_bean)
        snap = self._snapshot()
        try:
            self._append(f"{closed.isoformat()} close {path}\n")
            self._check(baseline=baseline_output)
        except BeanCheckError:
            self._restore(snap)
            raise
        except Exception:
            self._restore(snap)
            raise

    def rewrite_open_date(self, path: str, new_date: date) -> bool:
        """Rewrite the `YYYY-MM-DD open {path}` line in connector_accounts.bean
        to use `new_date`. Returns True if a line was changed.

        Needed because loans created today auto-scaffold their liability
        account with an Open dated today, but the initial-funding post is
        dated on the loan's historical funded_date — leaving bean-check
        complaining about "inactive account." Only touches our own file.
        """
        if not self.connector_accounts.exists():
            return False
        escaped = re.escape(path)
        pattern = re.compile(
            rf"^(\d{{4}}-\d{{2}}-\d{{2}})(\s+open\s+{escaped})(\s|$)",
            re.MULTILINE,
        )
        _, baseline_output = capture_bean_check(self.main_bean)
        snap = self._snapshot()
        try:
            text = self.connector_accounts.read_text(encoding="utf-8")
            new_text, n = pattern.subn(
                lambda m: f"{new_date.isoformat()}{m.group(2)}{m.group(3)}",
                text,
                count=1,
            )
            if n == 0:
                return False
            self.connector_accounts.write_text(new_text, encoding="utf-8")
            self._check(baseline=baseline_output)
            return True
        except BeanCheckError:
            self._restore(snap)
            raise
        except Exception:
            self._restore(snap)
            raise

    def write_balance_assertion(
        self,
        *,
        path: str,
        amount: str,
        currency: str = "USD",
        as_of: date | None = None,
    ) -> None:
        """Append a `{date} balance {path} {amount} {currency}` line."""
        when = as_of or date.today()
        _, baseline_output = capture_bean_check(self.main_bean)
        snap = self._snapshot()
        try:
            self._append(f"{when.isoformat()} balance {path} {amount} {currency}\n")
            self._check(baseline=baseline_output)
        except BeanCheckError:
            self._restore(snap)
            raise
        except Exception:
            self._restore(snap)
            raise

    def write_pad_and_balance(
        self,
        *,
        path: str,
        pad_source: str,
        amount: str,
        currency: str = "USD",
        as_of: date | None = None,
        comment: str | None = None,
    ) -> None:
        """Write a Beancount `pad` + `balance` pair so an account gets
        an opening-balance entry filled in automatically from
        ``pad_source`` (usually ``Equity:OpeningBalances:...``). The
        balance assertion is dated one day after the pad so Beancount
        knows to synthesize the interior posting on the pad's date.

        Snapshot+bean-check guard: on failure the file reverts
        byte-for-byte.
        """
        from datetime import timedelta as _td
        when = as_of or date.today()
        balance_date = when + _td(days=1)
        _, baseline_output = capture_bean_check(self.main_bean)
        snap = self._snapshot()
        try:
            block_lines = []
            if comment:
                block_lines.append(f"\n; {comment}\n")
            block_lines.append(
                f"{when.isoformat()} pad {path} {pad_source}\n"
            )
            block_lines.append(
                f"{balance_date.isoformat()} balance {path} "
                f"{amount} {currency}\n"
            )
            self._append("".join(block_lines))
            self._check(baseline=baseline_output)
        except BeanCheckError:
            self._restore(snap)
            raise
        except Exception:
            self._restore(snap)
            raise
